# Generated by Django 3.2.3 on 2022-01-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_document', models.CharField(choices=[("Carte Nationale d'Identité (CNI)", "Carte Nationale d'Identité (CNI)"), ('Passeport', 'Passeport'), ("Attestation d'Identité", "Attestation d'Identité"), ('Carte scolaire', 'Carte scolaire'), ('Carte bancaire', 'Carte bancaire/Carte magnétique'), ('Diplome', 'Diplome'), ('Livre/Cours/Cahier', 'Livre/Cours/Cahier'), ('Autres', 'Autres')], max_length=50)),
                ('nom_du_proprietaire', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
