# Generated by Django 3.2.3 on 2022-01-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_perdu', '0003_document_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='ville',
            field=models.CharField(max_length=50),
        ),
    ]
